name = "github-hosts"
main = "src/index.ts"
compatibility_date = "2024-10-28"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "public" }

# [vars]
# API_KEY = ""

[[kv_namespaces]]
binding = "github_hosts"
id = "34aa5e205cec4fc2b5e4738aea2f9318"


# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1

[triggers]
crons = ["0 */1 * * *"]
